---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_USER: hamza
  PGDATA: /data/postgres
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
data:
  init.sql: |
    -- Create multiple databases
    CREATE DATABASE IF NOT EXISTS customer;
    CREATE DATABASE IF NOT EXISTS notification;
    CREATE DATABASE IF NOT EXISTS order;
    CREATE DATABASE IF NOT EXISTS payment;
    CREATE DATABASE IF NOT EXISTS product;
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: hamza
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  labels:
    app: postgresql-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql-pod
  template:
    metadata:
      labels:
        app: postgresql-pod
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: PGDATA
          volumeMounts:
            - name: postgres-storage
              mountPath: /data/postgres
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: init-script
          configMap:
            name: postgres-init-script
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: postgresql-svc
spec:
  type: LoadBalancer
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgresql-pod


#To connect
#127.0.0.1:5432
#User: hamza
#Password: hamza