apiVersion: v1
data:
  application.yml: |
    server:
      port: 8888
    spring:
      profiles:
        active: native
      application:
        name: config-server
      cloud:
        config:
          server:
            native:
              search-locations: file:/config/configurations/
kind: ConfigMap
metadata:
  name: config-server-root-configuration
  namespace: e-commerce
