apiVersion: v1
data:
  application.yml: |
    eureka:
      instance:
        prefer-ip-address: true
      client:
        service-url:
          defaultZone: http://discovery-service-svc:8761/eureka
    name:
      value: hamza
    spring:
      cloud:
        config:
          override-system-properties: false

    management:
      tracing:
        sampling:
          probability: 1.0
      zipkin:
        tracing:
          endpoint: http://zipkin:9411/api/v2/spans
  customer-service.yml: |
    server:
      port: 8090
    spring:
      datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://postgresql:5432/customer
        username: hamza
        password: hamza
      jpa:
        hibernate:
          ddl-auto: update
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
  discovery-service.yml: |
    eureka:
      instance:
        prefer-ip-address: true
      client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
          defaultZone: http://discovery-service-svc:8761/eureka

    server:
      port: 8761
  gateway-service.yml: |
    server:
      port: 8222
    spring:
      cloud:
        gateway:
          discovery:
            locator:
              enabled: true
          routes:
            - id: customer-service
              uri: lb:http://CUSTOMER-SERVICE
              predicates:
                - Path=/api/v1/customers/**
            - id: order-service
              uri: lb:http://ORDER-SERVICE
              predicates:
                - Path=/api/v1/orders/**
            - id: order-lines-service
              uri: lb:http://ORDER-SERVICE
              predicates:
                - Path=/api/v1/order-lines/**
            - id: product-service
              uri: lb:http://PRODUCT-SERVICE
              predicates:
                - Path=/api/v1/products/**
            - id: payment-service
              uri: lb:http://PAYMENT-SERVICE
              predicates:
                - Path=/api/v1/payments/**
  notification-service.yml: |
    server:
      port: 8040
    spring:
      datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://postgresql:5432/notification
        username: hamza
        password: hamza
      jpa:
        hibernate:
          ddl-auto: update
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
      kafka:
        consumer:
          bootstrap-servers: kafka:9092
          group-id: paymentGroup,orderGroup
          auto-offset-reset: earliest
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
          properties:
            spring.json.trusted.packages: '*'
            spring.json.type.mapping: orderConfirmation:com.hamzaecommerce.kafka.order.OrderConfirmation,paymentConfirmation:com.hhamzacommerce.kafka.payment.PaymentConfirmation
      mail:
        host: mailer-dev
        port: 1025
        username: hamza
        password: hamza
        properties:
          mail:
            smtp:
              trust: "*"
            auth: true
            starttls:
              enabled: true
            connectiontimeout: 5000
            timeout: 3000
            writetimeout: 5000
  order-service.yml: |
    server:
      port: 8070
    spring:
      datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://postgresql:5432/order
        username: hamza
        password: hamza
      jpa:
        hibernate:
          ddl-auto: create
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
      kafka:
        producer:
          bootstrap-servers: kafka:9092
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
          properties:
            spring.json.type.mapping: orderConfirmation:com.hamzaecommerce.kafka.OrderConfirmation

    application:
      config:
        customer-url: http://gateway-service-svc:8222/api/v1/customers
        payment-url: http://gateway-service-svc:8222/api/v1/payments
        product-url: http://gateway-service-svc:8222/api/v1/products
  payment-service.yml: |
    server:
      port: 8060
    spring:
      datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://postgresql:5432/payment
        username: hamza
        password: hamza
      jpa:
        hibernate:
          ddl-auto: create
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
      kafka:
        producer:
          bootstrap-servers: kafka:9092
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
          properties:
            spring.json.type.mapping: paymentConfirmation:com.hamzaecommerce.notification.PaymentNotificationRequest
    application:
      config:
        product-url: http://gateway-service-svc:8222/api/v1/products
  product-service.yml: |+
    server:
      port: 8050
    spring:
      datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://postgresql:5432/product
        username: hamza
        password: hamza
      jpa:
        hibernate:
          ddl-auto: validate
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
      flyway:
        baseline-on-migrate: true
        enabled: true
        baseline-description: "init"
        baseline-version: 0
        user: ${spring.datasource.username}
        password: ${spring.datasource.password}

kind: ConfigMap
metadata:
  name: config-server-configurations
  namespace: e-commerce
